// <auto-generated />
namespace Oil.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LeaveOffice_ApplyPersonId_allowNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LeaveOffice_ApplyPersonId_allowNull));
        
        string IMigrationMetadata.Id
        {
            get { return "202001030132088_LeaveOffice_ApplyPersonId_allowNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
